"""0003

Revision ID: 130a924c039d
Revises: 7afb23a850ea
Create Date: 2023-12-02 21:41:43.665219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130a924c039d'
down_revision: Union[str, None] = '7afb23a850ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'season_number')
    op.drop_column('series', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('seasons', sa.Column('season_number', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
