"""0007

Revision ID: 4c200f8a6411
Revises: ee9b962b0523
Create Date: 2024-02-20 16:29:51.371278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c200f8a6411'
down_revision: Union[str, None] = 'ee9b962b0523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('seasons_number', sa.Integer(), nullable=True))
    op.drop_column('series', 'seasons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('seasons', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('series', 'seasons_number')
    # ### end Alembic commands ###
