"""0002

Revision ID: 7afb23a850ea
Revises: cd55552c6983
Create Date: 2023-12-02 20:02:43.746589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afb23a850ea'
down_revision: Union[str, None] = 'cd55552c6983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episodes', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('episodes', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
