"""0004

Revision ID: ce929b243d3c
Revises: 130a924c039d
Create Date: 2024-02-20 13:12:06.070388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce929b243d3c'
down_revision: Union[str, None] = '130a924c039d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episodes', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('series', sa.Column('title', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'title')
    op.alter_column('movies', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('episodes', sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('episodes_season_fkey', 'episodes', 'seasons', ['season'], ['id'])
    op.alter_column('episodes', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
