"""0006

Revision ID: ee9b962b0523
Revises: fae381430e25
Create Date: 2024-02-20 15:25:19.120090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9b962b0523'
down_revision: Union[str, None] = 'fae381430e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('season', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'episodes', 'seasons', ['season'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'episodes', type_='foreignkey')
    op.drop_column('episodes', 'season')
    # ### end Alembic commands ###
